[tool.black]
line-length = 120

[tool.isort]
profile = 'black'
src_paths = ['code', 'code/rmt', 'test']
skip_gitignore = false
line_length = 120
atomic = true
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'LOCALFOLDER', 'FIRSTPARTY']
known_local_folder = ['code/rmt', 'rmt']
